apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway-deployment
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
    spec:    
      nodeSelector:
        node_tag: mon
      containers:
        - name: pushgateway
          image: prom/pushgateway:latest
          ports:
            - containerPort: 9091
          
