apiVersion: v1
kind: Service
metadata:
  name: pushgateway-service
  namespace: monitoring  
spec:
  selector:
    app: pushgateway
  type: NodePort
  ports:
    - port: 8081
      targetPort: 9091
      nodePort: 30004