apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prod-bemily-file
  labels:
    node_tag: file
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: prod-bemily-file
  targetCPUUtilizationPercentage: 80