apiVersion: v1
kind: Service
metadata:
  name: bemily-bw
  labels:
    node_tag: bw
spec:
  type: NodePort
  selector:
    node_tag: bw
  ports:
    - name: bemily-bw
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30560
