apiVersion: apps/v1
kind: Deployment
metadata:
  name: bemily-bw
  labels:
    node_tag: bw
spec:
  replicas: 1
  selector:
    matchLabels:
      node_tag: bw
  template:
    metadata:
      labels:
        node_tag: bw
    spec:
      containers:
        - name: bemily-bw
          image: 193033533370.dkr.ecr.ap-northeast-2.amazonaws.com/bemily/bemily-bw:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 38080
          resources:
            requests:
              memory: "1500Mi"
              cpu: "500m"
            limits:
              memory: "2000Mi"
              cpu: "500m"
      nodeSelector:
        node_tag: bw