apiVersion: v1
kind: Service
metadata:
  name: bemily-auth
  labels:
    node_tag: auth
spec:
  type: NodePort
  selector:
    node_tag: auth
  ports:
    - name: bemily-auth
      port: 8080
      protocol: TCP
      targetPort: 8080