apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bemily-file
  labels:
    node_tag: file
spec:
  maxReplicas: 4
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: bemily-file
  targetCPUUtilizationPercentage: 80