apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bemily-api
  labels:
    node_tag: api
spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: bemily-api
  targetCPUUtilizationPercentage: 30