apiVersion: v1
kind: Service
metadata:
  name: prod-bemily-auth
  labels:
    node_tag: auth
spec:
  type: NodePort
  selector:
    node_tag: auth
  ports:
    - name: prod-bemily-auth
      port: 38081
      protocol: TCP
      nodePort: 30620
      targetPort: 38081
