apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bemily-auth
  labels:
    node_tag: auth
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: bemily-auth
  targetCPUUtilizationPercentage: 80