apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-bemily-auth
  labels:
    node_tag: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      node_tag: auth
  template:
    metadata:
      labels:
        node_tag: auth
    spec:
      containers:
        - name: prod-bemily-auth
          image: 193033533370.dkr.ecr.ap-northeast-2.amazonaws.com/bemily/auth-prod:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 38081
          resources:
            requests:
              memory: "2000Mi"
              cpu: "500m"
            limits:
              memory: "2300Mi"
              cpu: "700m"
      nodeSelector:
        node_tag: auth