apiVersion: v1
kind: Service
metadata:
  name: bemily-noti
  labels:
    node_tag: noti
    color : green
spec:
  type: NodePort
  selector:
    node_tag: noti
  ports:
    - name: bemily-noti
      port: 8080
      protocol: TCP
      targetPort: 8080