apiVersion: v1
kind: Service
metadata:
  name: bemily-noti
  labels:
    node_tag: noti
spec:
  type: NodePort
  selector:
    node_tag: noti
    color: blue
  ports:
    - name: bemily-noti
      port: 8080
      protocol: TCP
      nodePort: 30501
      targetPort:
