apiVersion: apps/v1
kind: Deployment
metadata:
  name: bemily-noti-blue
  labels:
    node_tag: noti
    color: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      node_tag: noti
      color: blue
  template:
    metadata:
      labels:
        node_tag: noti
        color: blue
    spec:
      containers:
        - name: bemily-noti
          image: 193033533370.dkr.ecr.ap-northeast-2.amazonaws.com/bemily/bemily-noti:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "1000Mi"
              cpu: "200m"
            limits:
              memory: "1200Mi"
              cpu: "230m"
      nodeSelector:
        node_tag: noti
