apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bemily-noti
  labels:
    node_tag: noti
    color : blue
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bemily-noti
  targetCPUUtilizationPercentage: 80
