apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: curator
  namespace: monitoring
  labels:
    k8s-app: curator
    node_tag: curator
spec:
  schedule: "0 16 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: bobrik/curator:5.8.1
            name: curator
            args: ["--config", "/etc/config/config.yml", "/etc/config/action_file.yml"]
            volumeMounts:
            - name: config
              mountPath: /etc/config
          volumes:
          - name: config
            configMap:
              name: curator-config
          restartPolicy: OnFailure
          nodeSelector:
              node_tag: mon
