apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bemily-sd
  labels:
    node_tag: sd
spec:
  maxReplicas: 4
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: bemily-sd
  targetCPUUtilizationPercentage: 50
