apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-bemily-noti-green
  labels:
    node_tag: noti
    color: green
spec:
  replicas: 2
  selector:
    matchLabels:
      node_tag: noti
      color: green
  template:
    metadata:
      labels:
        node_tag: noti
        color: green
    spec:
      containers:
        - name: prod-bemily-noti
          image: 193033533370.dkr.ecr.ap-northeast-2.amazonaws.com/bemily/bemily-noti-prod:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "2000Mi"
              cpu: "500m"
            limits:
              memory: "2300Mi"
              cpu: "500m"
      nodeSelector:
        node_tag: noti
