apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prod-bemily-noti
  labels:
    node_tag: noti
    color : green
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prod-bemily-noti
  targetCPUUtilizationPercentage: 80
