apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bemily-noti
  labels:
    node_tag: noti
    color : green
spec:
  maxReplicas: 5
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bemily-noti
  targetCPUUtilizationPercentage: 80
