apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prod-bemily-sd
  labels:
    node_tag: sd
spec:
  maxReplicas: 3
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: prod-bemily-sd
  targetCPUUtilizationPercentage: 80
