apiVersion: v1
kind: Service
metadata:
  name: prod-bemily-sd
  labels:
    node_tag: sd
spec:
  type: NodePort
  selector:
    node_tag: sd
  ports:
    - name: prod-bemily-sd
      port: 8080
      protocol: TCP
      nodePort: 30600
      targetPort: 8080
