apiVersion: apps/v1
kind: Deployment
metadata:
  name: bemily-noti-blue
  labels:
    node_tag: noti
    color: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      node_tag: noti
      color: blue
  template:
    metadata:
      labels:
        node_tag: noti
        color: blue
    spec:
      containers:
        - name: bemily-noti
          image: 193033533370.dkr.ecr.ap-northeast-2.amazonaws.com/bemily/bemily-noti:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "1500Mi"
              cpu: "500m"
            limits:
              memory: "2000Mi"
              cpu: "500m"
      nodeSelector:
        node_tag: noti

---
apiVersion: v1
kind: Service
metadata:
  name: bemily-noti
  labels:
    node_tag: noti
spec:
  type: NodePort
  selector:
    node_tag: noti
    color: blue
  ports:
    - name: bemily-noti
      port: 8080
      protocol: TCP
      nodePort: 30501
      targetPort:

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bemily-noti
  labels:
    node_tag: noti
    color : blue
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bemily-noti
  targetCPUUtilizationPercentage: 80
