apiVersion: v1
kind: Service
metadata:
  name: bemily-sd
  labels:
    node_tag: sd
spec:
  type: NodePort
  selector:
    node_tag: sd
  ports:
    - name: bemily-sd
      port: 8080
      protocol: TCP
      targetPort: 8080