apiVersion: apps/v1
kind: Deployment
metadata:
  name: bemily-api
  labels:
    node_tag: api
spec:
  replicas: 4
  selector:
    matchLabels:
      node_tag: api
  template:
    metadata:
      labels:
        node_tag: api
    spec:
      containers:
        - name: bemily-api
          image: 193033533370.dkr.ecr.ap-northeast-2.amazonaws.com/bemily/bemily_api-prod:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7000
      nodeSelector:
        node_tag: api
