apiVersion: v1
kind: Service
metadata:
  name: prod-bemily-api
  labels:
    node_tag: api
spec:
  type: NodePort
  selector:
    node_tag: api
  ports:
    - name: prod-bemily-api
      port: 7000
      protocol: TCP
      nodePort: 30680
      targetPort: 7000
