apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bemily-noti
  labels:
    node_tag: noti
spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
  targetCPUUtilizationPercentage: 30
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: bemily-noti
    labels:
      node_tag: noti
  spec:
    replicas: 2
    selector:
      matchLabels:
        node_tag: noti
    template:
      metadata:
        labels:
          node_tag: noti
      spec:
        containers:
          - name: bemily-noti
            image: 193033533370.dkr.ecr.ap-northeast-2.amazonaws.com/bemily/bemily-noti:latest
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
        nodeSelector:
          node_tag: noti