apiVersion: v1
kind: Service
metadata:
  name: bemily-api
  labels:
    node_tag: api
spec:
  type: NodePort
  selector:
    node_tag: api
  ports:
    - name: bemily-api
      port: 8080
      protocol: TCP
      targetPort: 8080

