apiVersion: apps/v1
kind: Deployment
metadata:
  name: bemily-api
  labels:
    node_tag: api
spec:
  replicas: 2
  selector:
    matchLabels:
      node_tag: api
  template:
    metadata:
      labels:
        node_tag: api
    spec:
      containers:
        - name: bemily-api
          image: 193033533370.dkr.ecr.ap-northeast-2.amazonaws.com/bemily/bemily_api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      nodeSelector:
        node_tag: api